import { ParticipantEntry, SponsorItem, PrizeItem, Criterion } from './types';

export const OFFICIAL_PRIZES: PrizeItem[] = [
  {
    rank: 1,
    title: 'Maharashtra Rajya Mahavijeta (1st Place)',
    titleMr: 'महाराष्ट्र राज्य महाविजेता (प्रथम क्रमांक)',
    cashAmount: 51000,
    cashText: '₹51,000 Cash',
    cashTextMr: '₹51,000 रोख पारितोषिक',
    perks: ['Grand Gold Plated Trophy', 'State-wide Media Coverage', 'Official Certificate of Honor'],
    perksMr: ['मानाची सुवर्णजडित ट्रॉफी', 'राज्यस्तरीय वृत्तपत्र व माध्यम प्रसिद्धी', 'अधिकृत सन्मानपत्र'],
    badgeColor: 'bg-amber-600 text-white',
  },
  {
    rank: 2,
    title: '2nd Place (Dvitiya Puraskar)',
    titleMr: 'द्वितीय क्रमांक',
    cashAmount: 31000,
    cashText: '₹31,000 Cash',
    cashTextMr: '₹31,000 रोख पारितोषिक',
    perks: ['Silver Plated Trophy', 'Official Certificate of Honor', 'State Recognition'],
    perksMr: ['मानाची रजत ट्रॉफी', 'अधिकृत सन्मानपत्र', 'राज्यस्तरीय सन्मान गौरव'],
    badgeColor: 'bg-slate-500 text-white',
  },
  {
    rank: 3,
    title: '3rd Place (Tritiya Puraskar)',
    titleMr: 'तृतीय क्रमांक',
    cashAmount: 21000,
    cashText: '₹21,000 Cash',
    cashTextMr: '₹21,000 रोख पारितोषिक',
    perks: ['Bronze Plated Trophy', 'Official Certificate of Honor', 'State Recognition'],
    perksMr: ['कांस्य ट्रॉफी', 'अधिकृत सन्मानपत्र', 'राज्यस्तरीय सन्मान गौरव'],
    badgeColor: 'bg-amber-800 text-white',
  },
  {
    rank: 4,
    title: '4th to 10th Place (State Consolation Awards)',
    titleMr: '4था ते 10वा क्रमांक (राज्यस्तरीय गुणवत्ता पुरस्कार)',
    cashAmount: 5000,
    cashText: '₹5,000 Cash Each (7 Winners)',
    cashTextMr: 'प्रत्येकी ₹5,000 रोख (7 विजेते)',
    perks: ['Maha Lokutsav Memento', 'Certificate of Merit', 'Digital Showcase'],
    perksMr: ['महा लोकोत्सव सन्मानचिन्ह', 'गुणवत्ता प्रमाणपत्र', 'डिजिटल दालन गौरव'],
    badgeColor: 'bg-stone-700 text-white',
  },
];

export const JUDGING_CRITERIA_LIST: Criterion[] = [
  {
    id: 'crit-1',
    name: 'Concept & Creativity',
    nameMr: 'संकल्पना व कल्पकता',
    description: 'Originality of story, theme, cultural resonance, and depth of imagination.',
    descriptionMr: 'सजावटीमागील मूळ विचार, संदेश, सामाजिक किंवा पौराणिक संकल्पनेची मांडणी.',
    maxScore: 10,
    weight: 0.25,
    iconName: 'Sparkles',
  },
  {
    id: 'crit-2',
    name: 'Craftsmanship & Detailing',
    nameMr: 'हस्तकला व फिनिशिंग',
    description: 'Structural precision, finishing, artistry, handmade elements, and aesthetic balance.',
    descriptionMr: 'तयार केलेल्या देखाव्याची कारागिरी, अचूकता, सुबकता आणि सुसंवाद.',
    maxScore: 10,
    weight: 0.25,
    iconName: 'Palette',
  },
  {
    id: 'crit-3',
    name: 'Eco-Friendliness & Materials',
    nameMr: 'पर्यावरणपूरकता व साहित्य',
    description: 'Clay (Shadu) idol, cloth, bamboo, paper pulp, seed paper; zero thermocol or plastic.',
    descriptionMr: 'शाडू माती मूर्ती, कागदी लगदा, फुले, कापड यांसारख्या निसर्गस्नेही घटकांचा वापर.',
    maxScore: 10,
    weight: 0.20,
    iconName: 'Leaf',
  },
  {
    id: 'crit-4',
    name: 'Lighting & Presentation',
    nameMr: 'प्रकाशयोजना व सादरीकरण',
    description: 'Lighting design, color coherence, neatness, framing, and visual ambience.',
    descriptionMr: 'रंगसंगती, प्रकाशयोजना (Lighting), मांडणीचे सौंदर्य आणि संपूर्ण दृश्य प्रभाव.',
    maxScore: 10,
    weight: 0.15,
    iconName: 'Sun',
  },
  {
    id: 'crit-5',
    name: 'Uniqueness & Wow Factor',
    nameMr: 'नाविन्यता व वेगळेपण',
    description: 'Novel approach, emotional impact, and unforgettable artistic impression.',
    descriptionMr: 'नेहमीपेक्षा वेगळा विचार आणि प्रेक्षकांना मंत्रमुग्ध करणारी नाविन्यपूर्ण कल्पना.',
    maxScore: 10,
    weight: 0.15,
    iconName: 'Award',
  },
];

export const SPONSORS_LIST: SponsorItem[] = [
  {
    id: 'sp-1',
    name: 'Chitale Bandhu Mithaiwale',
    tier: 'TITLE',
    logoUrl: '/sponsors/chitale.png',
    websiteUrl: 'https://chitalebandhu.in',
    sponsoredCategory: 'Title Partner & Grand 1st Prize',
    sponsoredCategoryMr: 'मुख्य प्रायोजक व महाविजेता पारितोषिक',
    description: 'Maharashtra’s iconic heritage sweetmaker celebrating sweet traditions for over 8 decades.',
    descriptionMr: 'महाराष्ट्राचे लाडके मिष्ठान्न ब्रँड, 8 दशकांपासून परंपरेची गोडी जपणारे चितळे बंधू.',
  },
  {
    id: 'sp-2',
    name: 'PNG Jewellers',
    tier: 'POWERED_BY',
    logoUrl: '/sponsors/png.png',
    websiteUrl: 'https://pngjewellers.com',
    sponsoredCategory: 'Official Trophy & Gold Partner',
    sponsoredCategoryMr: 'अधिकृत सुवर्ण ट्रॉफी व सह-प्रायोजक',
    description: 'Purity, Trust and 190+ years of Royal Maharashtrian Jewellery legacy.',
    descriptionMr: 'शुद्धता, विश्वास आणि 190+ वर्षांचा सुवर्ण वारसा जपणारे पी एन जी ज्वेलर्स.',
  },
  {
    id: 'sp-3',
    name: 'Suhana Spices',
    tier: 'GOLD',
    logoUrl: '/sponsors/suhana.png',
    websiteUrl: 'https://suhana.co.in',
    sponsoredCategory: 'Best Eco-Friendly Decoration Award',
    sponsoredCategoryMr: 'सर्वोत्कृष्ट पर्यावरणपूरक सजावट पुरस्कार',
    description: 'Delivering authentic flavors and fragrant Maharashtrian masalas worldwide.',
    descriptionMr: 'घरचा अस्सल स्वाद आणि रुचकर खाद्यपरंपरेचा सुगंध देणारे सुहाना मसाले.',
  },
  {
    id: 'sp-4',
    name: 'Saraswat Bank',
    tier: 'ASSOCIATE',
    logoUrl: '/sponsors/saraswat.png',
    websiteUrl: 'https://saraswatbank.com',
    sponsoredCategory: 'Digital Banking & Verification Partner',
    sponsoredCategoryMr: 'डिजिटल बँकिंग व पडताळणी सहयोगी',
    description: 'India’s largest urban co-operative bank supporting Marathi culture and enterprise.',
    descriptionMr: 'महाराष्ट्राच्या प्रगतीचा विश्वासू भागीदार, सर्वात मोठी अग्रगण्य सहकारी बँक.',
  },
];

export const INITIAL_ENTRIES: ParticipantEntry[] = [
  // --- Dedicated Test Entries for Local Testing ---
  {
    id: 'entry-test-1',
    ticketId: 'LOK-2026-1001',
    fullName: 'सचिन दत्तात्रय पाटील (Sachin Dattatraya Patil)',
    phone: '9999999999',
    email: 'sachin.patil@example.com',
    district: 'Pune',
    city: 'Kothrud, Pune',
    address: 'Plot 45, Mayur Colony, Kothrud, Pune 411038',
    category: 'HOUSEHOLD',
    idolType: 'SHADU_MATI_CLAY',
    themeTitle: 'ऐतिहासिक शिवकालीन रायगड दरबार देखावा',
    themeDescription: 'छत्रपती शिवाजी महाराजांच्या मेघडंबरीची पर्यावरणपूरक भव्य प्रतिकृती, बांबू व मातीचे घटक.',
    materialsUsed: 'शाडू माती मूर्ती, बांबू, ज्यूट दोरी, पर्यावरणपूरक रंग, मातीचे दिवे.',
    photoUrls: [
      'https://images.unsplash.com/photo-1567591370504-20a2e7c54ef5?auto=format&fit=crop&w=1200&q=80',
    ],
    videoUrl: 'https://www.youtube.com/watch?v=sample1',
    entryFee: 99,
    paymentStatus: 'COMPLETED',
    status: 'APPROVED',
    createdAt: '2026-09-10T10:00:00Z',
  },
  {
    id: 'entry-test-2',
    ticketId: 'LOK-2026-2002',
    fullName: 'श्री गणेश मित्र मंडळ (Shree Ganesh Mitra Mandal)',
    phone: '9888888888',
    email: 'mitramandal.mumbai@example.com',
    district: 'Mumbai City',
    city: 'Dadar, Mumbai',
    address: 'Shree Ganesh Nagar, Ranade Road, Dadar West, Mumbai 400028',
    category: 'SARVAJANIK_MANDAL',
    idolType: 'ECO_FRIENDLY_PAPER_PULP',
    themeTitle: 'सुवर्ण मंदिर प्रतिकृती व भव्य पारंपरिक रोषणाई',
    themeDescription: 'अमृतसर सुवर्ण मंदिराची पर्यावरणपूरक कागदी लगद्याची सुंदर प्रतिकृती व शांत प्रकाशयोजना.',
    materialsUsed: 'कागदी लगदा, कापड, लाकडी फ्रेम, एलईडी रोषणाई.',
    photoUrls: [
      'https://images.unsplash.com/photo-1606293926075-69a00dbfde81?auto=format&fit=crop&w=1200&q=80',
    ],
    videoUrl: 'https://www.youtube.com/watch?v=sample2',
    entryFee: 99,
    paymentStatus: 'COMPLETED',
    status: 'APPROVED',
    createdAt: '2026-09-11T12:00:00Z',
  },
  {
    id: 'entry-test-3a',
    ticketId: 'LOK-2026-3001',
    fullName: 'आनंद महादेव सावंत (Anand Mahadev Sawant)',
    phone: '9777777777',
    email: 'anand.sawant@example.com',
    district: 'Kolhapur',
    city: 'Rajarampuri, Kolhapur',
    address: 'Tarabai Park, Kolhapur 416003',
    category: 'HOUSEHOLD',
    idolType: 'SHADU_MATI_CLAY',
    themeTitle: 'अंबाबाई महालक्ष्मी दीपस्तंभ देखावा',
    themeDescription: '१०८ पारंपरिक पितळी दिव्यांची आरास व राजस्थानी मंदिर कोरीव काम.',
    materialsUsed: 'शाडू माती, लाकूड, पितळी दिवे.',
    photoUrls: [
      'https://images.unsplash.com/photo-1599827552599-eafeedb4231f?auto=format&fit=crop&w=1200&q=80',
    ],
    entryFee: 99,
    paymentStatus: 'COMPLETED',
    status: 'APPROVED',
    createdAt: '2026-09-12T09:30:00Z',
  },
  {
    id: 'entry-test-3b',
    ticketId: 'LOK-2026-3002',
    fullName: 'सावंत कुटुंब पर्यावरणपूरक गणेशोत्सव',
    phone: '9777777777',
    email: 'anand.sawant@example.com',
    district: 'Kolhapur',
    city: 'Rajarampuri, Kolhapur',
    address: 'Tarabai Park, Kolhapur 416003',
    category: 'HOUSEHOLD',
    idolType: 'ECO_FRIENDLY_PAPER_PULP',
    themeTitle: 'निसर्ग संवर्धन व हरित महाराष्ट्र संकल्पना',
    themeDescription: 'रोपवाटिका व खतांपासून तयार केलेली पर्यावरणस्नेही आरास.',
    materialsUsed: 'जिवंत झाडे, कागदी लगदा, माती.',
    photoUrls: [
      'https://images.unsplash.com/photo-1600093463592-8e36ae95ef56?auto=format&fit=crop&w=1200&q=80',
    ],
    entryFee: 99,
    paymentStatus: 'COMPLETED',
    status: 'APPROVED',
    createdAt: '2026-09-12T10:00:00Z',
  },
  {
    id: 'entry-test-4',
    ticketId: 'LOK-2026-4004',
    fullName: 'राहुल विठ्ठल मोहिते (Rahul Vitthal Mohite)',
    phone: '9666666666',
    email: 'rahul.mohite@example.com',
    district: 'Nashik',
    city: 'Gangapur Road, Nashik',
    address: 'Shree Residency, Nashik 422005',
    category: 'HOUSEHOLD',
    idolType: 'SHADU_MATI_CLAY',
    themeTitle: 'नाशिक कुंभमेळा व गोदावरी घाट देखावा',
    themeDescription: 'गोदावरी आरती व घाटांचे दृश्य.',
    materialsUsed: 'शाडू माती, कापड.',
    photoUrls: [],
    entryFee: 99,
    paymentStatus: 'PENDING',
    status: 'PENDING_VERIFICATION',
    createdAt: '2026-09-14T11:00:00Z',
  },
  // --- Top 10 Declared State Champions ---
  {
    id: 'entry-101',
    ticketId: 'LOK-2026-196450',
    fullName: 'Shrikant Ramchandra Joshi',
    phone: '9822019941',
    email: 'shrikant.joshi@example.com',
    district: 'Pune',
    city: 'Sadashiv Peth, Pune',
    address: 'Flat 4, Shreeram Niwas, Perugate, Pune 411030',
    category: 'HOUSEHOLD',
    idolType: 'SHADU_MATI_CLAY',
    themeTitle: 'ऐतिहासिक शिवकालीन रायगड राजसभा व पर्यावरणस्नेही मेघडंबरी (Shivkalin Raigad Darbar & Handcrafted Meghadambari)',
    themeDescription: 'छत्रपती शिवाजी महाराजांच्या ३५० व्या शिवराज्याभिषेक वर्षानिमित्त ऐतिहासिक रायगड राजसभेची आणि मानाच्या ३२ मण सुवर्णसिंहासनाच्या मेघडंबरीची भव्य व सुबक प्रतिकृती. संपूर्ण देखावा १००% पर्यावरणस्नेही असून पुनर्वापर केलेल्या बांबूच्या पट्ट्या, नैसर्गिक ज्यूट दोरी, नारळाच्या करवंट्यांचे कोरीव काम आणि हस्तनिर्मित मातीच्या स्तंभांनी साकारला आहे. गणरायाचे तेज नैसर्गिक हळद, गेरू आणि सुकलेल्या झेंडूच्या फुलांच्या सेंद्रिय रंगांनी उजळले आहे.',
    materialsUsed: '१००% शाडू माती मूर्ती, बांबू, सेंद्रिय ज्यूट दोरी, नारळाच्या करवंट्यांचे नक्षीकाम, नैसर्गिक गेरू व हळद रंग, १००% थर्माकोल व प्लास्टिक मुक्त, पारंपरिक पितळी व मातीचे नंदादीप.',
    photoUrls: [
      'https://images.unsplash.com/photo-1567591370504-20a2e7c54ef5?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1599827552599-eafeedb4231f?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1600093463592-8e36ae95ef56?auto=format&fit=crop&w=1200&q=80',
    ],
    videoUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    entryFee: 99,
    paymentStatus: 'COMPLETED',
    razorpayOrderId: 'order_Pune_9012',
    razorpayPaymentId: 'pay_Pune_8911',
    status: 'APPROVED',
    finalScore: 9.6,
    finalRank: 1,
    evaluationsCount: 4,
    createdAt: '2026-09-02T10:30:00Z',
  },
  {
    id: 'entry-102',
    ticketId: 'LOK-2026-168631',
    fullName: 'Vaishali Anand Salunkhe',
    phone: '9765412390',
    email: 'vaishali.salunkhe@example.com',
    district: 'Kolhapur',
    city: 'Rajarampuri, Kolhapur',
    address: 'Plot 12, Tarabai Park, Kolhapur 416003',
    category: 'HOUSEHOLD',
    idolType: 'SHADU_MATI_CLAY',
    themeTitle: 'करवीर निवासिनी श्री अंबाबाई मंदिर हेमाडपंथी महाद्वार व १०८ दीपमाळ (Kolhapur Mahalakshmi Architecture & 108 Deepotsav)',
    themeDescription: 'कोल्हापूरच्या ऐतिहासिक हेमाडपंथी महालक्ष्मी मंदिराच्या काळ्या पाषाणातील कोरीव खांबांची आणि महाद्वाराची अत्यंत रेखीव प्रतिकृती. नैसर्गिक काळी माती, पुनर्चक्रित लाकूड आणि पारंपरिक डिंक-खडूच्या मिश्रणातून कोरलेले खांब असून, १०८ अखंड तेवणाऱ्या अस्सल पितळी समया आणि तेलवातींच्या मंद प्रकाशाने संपूर्ण गर्भगृह अलौकिक व शांत आध्यात्मिक वातावरणात न्हाऊन निघते.',
    materialsUsed: '१००% शाडू माती मूर्ती, हस्तकला कोरीव लाकूड, काळ्या मातीची प्लास्टरिंग, १०८ अस्सल पितळी नंदादीप, शुद्ध तिळाचे तेल, झेंडू व शेवंतीची ताजी फुले.',
    photoUrls: [
      'https://images.unsplash.com/photo-1606293926075-69a00dbfde81?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1567591370504-20a2e7c54ef5?auto=format&fit=crop&w=1200&q=80',
    ],
    videoUrl: 'https://www.youtube.com/watch?v=sample2',
    entryFee: 99,
    paymentStatus: 'COMPLETED',
    razorpayOrderId: 'order_Kolhapur_3211',
    razorpayPaymentId: 'pay_Kolhapur_4432',
    status: 'APPROVED',
    finalScore: 9.4,
    finalRank: 2,
    evaluationsCount: 3,
    createdAt: '2026-09-03T14:15:00Z',
  },
  {
    id: 'entry-103',
    ticketId: 'LOK-2026-136582',
    fullName: 'Mangesh Devidas Parab',
    phone: '9820156789',
    email: 'mangesh.parab@example.com',
    district: 'Mumbai Suburban',
    city: 'Vile Parle East, Mumbai',
    address: 'B-14, Shree Ganesh Krupa, Hanuman Road, Mumbai 400057',
    category: 'HOUSEHOLD',
    idolType: 'ECO_FRIENDLY_PAPER_PULP',
    themeTitle: 'इंद्रायणी काठ ते चंद्रभागा: आषाढी वारी संतमंडळ दिंडी देखावा (Warkari Sant Samagam & Pandharpur Palkhi Journey)',
    themeDescription: 'महाराष्ट्राच्या ८०० वर्षांच्या अखंड वारकरी भक्तीपरंपरेचे सजीव दर्शन घडवणारा गतिमान देखावा. जुन्या वर्तमानपत्रांच्या लगद्यापासून आणि गव्हाच्या खळीपासून हस्तकलेने घडवलेल्या ४० सुबक वारकरी मूर्ती—टाळ-मृदंग, वीणा व पताका हाती घेऊन संत ज्ञानेश्वर-तुकारामांची पालखी पंढरीकडे नेताना दाखवल्या आहेत. नदीकाठच्या पहाटेच्या धुक्याची व सूर्योदयाची मंद रोषणाई आणि पार्श्वभागी संतांचे अभंग संपूर्ण वातावरणात भक्तीरस निर्माण करतात.',
    materialsUsed: '१००% पर्यावरणस्नेही कागदी लगदा मूर्ती, नैसर्गिक सुती कापडाची वस्त्रे, गव्हाची खळ (लायी), लाकडी काठ्या, निसर्गस्नेही सेंद्रिय रंग, ऊर्जा-बचत सूर्योदय वॉर्म एलईडी.',
    photoUrls: [
      'https://images.unsplash.com/photo-1599827552599-eafeedb4231f?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1600093463592-8e36ae95ef56?auto=format&fit=crop&w=1200&q=80',
    ],
    videoUrl: 'https://www.youtube.com/watch?v=sample3',
    entryFee: 99,
    paymentStatus: 'COMPLETED',
    razorpayOrderId: 'order_Mumbai_1190',
    razorpayPaymentId: 'pay_Mumbai_7721',
    status: 'APPROVED',
    finalScore: 9.2,
    finalRank: 3,
    evaluationsCount: 3,
    createdAt: '2026-09-04T09:00:00Z',
  },
  {
    id: 'entry-104',
    ticketId: 'LOK-2026-734767',
    fullName: 'Aniket Surendra Deshmukh',
    phone: '9422334455',
    email: 'aniket.d@example.com',
    district: 'Nagpur',
    city: 'Dharampeth, Nagpur',
    address: '22, Orange City Enclave, Nagpur 440010',
    category: 'HOUSEHOLD',
    idolType: 'SHADU_MATI_CLAY',
    themeTitle: 'ताडोबा-अंधारी व्याघ्र प्रकल्प व विदर्भ जैवविविधता संवर्धन (Tadoba Forest Sanctuary & Living Green Canopy)',
    themeDescription: 'मध्य भारतातील समृद्ध वन्यजीव आणि ताडोबाच्या अरण्य परिसंस्थेला समर्पित जिवंत निसर्ग देखावा. कोणत्याही कृत्रिम साहित्याशिवाय तब्बल ५१ जिवंत औषधी वनस्पती (तुळस, दुर्वा, बेल, शतावरी), नारळाच्या काथ्या, बांबूच्या जाळ्या आणि जंगलातील पडलेली सुकी सागाची पाने वापरून घनदाट अरण्याची आरास उभारली आहे. बाप्पाच्या चरणी ‘झाडे लावा, वनसंपदा वाचवा’ हा पर्यावरण रक्षणाचा ठाम संदेश दिला आहे.',
    materialsUsed: '१००% शाडू माती मूर्ती (आतमध्ये बियाणे समाविष्ट - Tree Ganesha), ५१ जिवंत औषधी कुंड्या, नारळाची काथ्या, सागाची वाळलेली पाने, बांबू, मटका ठिबक सिंचन.',
    photoUrls: [
      'https://images.unsplash.com/photo-1606293926075-69a00dbfde81?auto=format&fit=crop&w=1200&q=80',
    ],
    entryFee: 99,
    paymentStatus: 'COMPLETED',
    razorpayOrderId: 'order_Nagpur_7712',
    razorpayPaymentId: 'pay_Nagpur_9921',
    status: 'APPROVED',
    finalScore: 8.9,
    finalRank: 4,
    evaluationsCount: 2,
    createdAt: '2026-09-04T16:20:00Z',
  },
  {
    id: 'entry-105',
    ticketId: 'LOK-2026-360161',
    fullName: 'Suhas Eknath Kadam',
    phone: '9921345566',
    email: 'suhas.kadam@example.com',
    district: 'Satara',
    city: 'Wai, Satara',
    address: 'Ghat Road, Wai, Satara 412803',
    category: 'HOUSEHOLD',
    idolType: 'SHADU_MATI_CLAY',
    themeTitle: 'वाईचा कृष्णामाई घाट, पारंपरिक ढोल-ताशा वादन व जलपूजन (Historic Wai Krishna Ghat & Dhol-Tasha Heritage)',
    themeDescription: 'सातारा जिल्ह्यातील वाईच्या ऐतिहासिक कृष्णा नदी घाटावरील दगडी पायऱ्या, महागणपती मंदिराची छत्री आणि महाराष्ट्राच्या वीरश्रीपूर्ण ढोल-ताशा संस्कृतीचा अप्रतिम संगम. स्थानिक कारागिरांनी टाकाऊ लाकूड, कातडे व पितळी तारांतून हाताने तयार केलेले सूक्ष्म ढोल-ताशा वाद्य संच आणि वाहत्या पाण्याच्या पुनर्चक्रित धारेतून जलसंधारणाचा संदेश देणारा हा अद्वितीय देखावा आहे.',
    materialsUsed: '१००% शाडू माती मूर्ती, वाळू, गारगोटीचे दगड, हस्तनिर्मित लाकडी सूक्ष्म वाद्ये, तांब्या-पितळेचे कलश, सौरऊर्जेवर चालणारा पाण्याचा पाझर.',
    photoUrls: [
      'https://images.unsplash.com/photo-1567591370504-20a2e7c54ef5?auto=format&fit=crop&w=1200&q=80',
    ],
    entryFee: 99,
    paymentStatus: 'COMPLETED',
    razorpayOrderId: 'order_Satara_3411',
    razorpayPaymentId: 'pay_Satara_8871',
    status: 'APPROVED',
    finalScore: 8.8,
    finalRank: 5,
    evaluationsCount: 2,
    createdAt: '2026-09-05T11:45:00Z',
  },
  {
    id: 'entry-106',
    ticketId: 'LOK-2026-650167',
    fullName: 'Balasaheb Tukaram More',
    phone: '9890123456',
    email: 'balasaheb.more@example.com',
    district: 'Nashik',
    city: 'Panchavati, Nashik',
    address: 'Ramkund Parisar, Panchavati, Nashik 422003',
    category: 'SARVAJANIK_MANDAL',
    idolType: 'SHADU_MATI_CLAY',
    themeTitle: 'गोदावरी अमृतधारा व जलपुनर्भरण जनआंदोलन देखावा (Godavari River Basin Restoration & Rainwater Harvesting)',
    themeDescription: 'नाशिकच्या पवित्र गोदावरी नदीचे प्रदूषणमुक्ती अभियान व दुष्काळमुक्तीसाठी "छतावरील पावसाचे पाणी साठवण" (Rainwater Harvesting) ही संकल्पना मांडणारा भव्य समाजप्रबोधक देखावा. पाणी अडवा, पाणी जिरवा या तंत्रज्ञानाचे प्रात्यक्षिक नैसर्गिक खादीचे कापड, मातीचे थर आणि रिसायकल केलेल्या पाण्याच्या कारंज्याद्वारे जिवंत केले आहे.',
    materialsUsed: '१००% शाडू माती मूर्ती, पर्यावरणपूरक खादी कापड, मातीचे थर, नारळाची जूट, हस्तनिर्मित पर्यावरण पत्रके, एलईडी वॉटर रिफ्लेक्टर.',
    photoUrls: [
      'https://images.unsplash.com/photo-1599827552599-eafeedb4231f?auto=format&fit=crop&w=1200&q=80',
    ],
    entryFee: 99,
    paymentStatus: 'COMPLETED',
    razorpayOrderId: 'order_Nashik_9011',
    razorpayPaymentId: 'pay_Nashik_3311',
    status: 'APPROVED',
    finalScore: 8.7,
    finalRank: 6,
    evaluationsCount: 2,
    createdAt: '2026-09-05T15:10:00Z',
  },
  {
    id: 'entry-107',
    ticketId: 'LOK-2026-313804',
    fullName: 'Dhananjay Raghunath Shinde',
    phone: '9822445566',
    email: 'dhananjay.shinde@example.com',
    district: 'Chhatrapati Sambhajinagar',
    city: 'CIDCO, Chhatrapati Sambhajinagar',
    address: 'N-4, CIDCO, Chhatrapati Sambhajinagar 431003',
    category: 'HOUSEHOLD',
    idolType: 'SHADU_MATI_CLAY',
    themeTitle: 'जागतिक वारसा वेरूळचे कैलास लेणे एकाश्म पाषाण शिल्प (UNESCO Ellora Kailash Temple Monolithic Architecture)',
    themeDescription: 'युनेस्को जागतिक वारसा असलेल्या वेरूळ येथील १६ व्या कैलास लेण्याच्या अखंड पाषाणातील कोरीव रचनेची शाडू माती आणि सेंद्रिय खड्यांच्या रंगात साकारलेली विलोभनीय प्रतिकृती. पर्वताच्या वरून खाली कोरत आणलेल्या अद्वितीय भारतीय स्थापत्यकलेचे स्तंभ, हत्तींची रांग आणि देवकोष्टके हाताने सुबकपणे कोरली आहेत.',
    materialsUsed: '१००% शाडू माती मूर्ती, नैसर्गिक लाल-काळी मातीचा लेप, लाकडाचा अंतर्गत सांगाडा, नैसर्गिक डिंक रंग, तेलाच्या पणत्यांचे सौम्य प्रकाश कोन.',
    photoUrls: [],
    entryFee: 99,
    paymentStatus: 'COMPLETED',
    status: 'APPROVED',
    finalScore: 8.6,
    finalRank: 7,
    evaluationsCount: 2,
    createdAt: '2026-09-06T10:00:00Z',
  },
  {
    id: 'entry-108',
    ticketId: 'LOK-2026-777638',
    fullName: 'Pratibha Gajanan Kulkarni',
    phone: '9833556677',
    email: 'pratibha.kulkarni@example.com',
    district: 'Thane',
    city: 'Naupada, Thane',
    address: 'Gokhale Road, Naupada, Thane West 400602',
    category: 'HOUSEHOLD',
    idolType: 'ECO_FRIENDLY_PAPER_PULP',
    themeTitle: 'कोकणातील पारंपरिक जांभा दगड कौलारू घर व निसर्ग आरास (Konkan Red Laterite Heritage House & Agro-Artistry)',
    themeDescription: 'कोकणातील निसर्गाच्या कुशीतील पारंपरिक जांभा (चिरेबंदी) दगडांचे कौलारू घर, तुळशी वृंदावन आणि नारळी-सुपारीच्या बागांची मनमोहक आरास. संपूर्ण सजावटीत सुपारीच्या झावळ्या, नारळाच्या करवंट्यांचे लॅम्पशेड्स, शेतातील पेंढा आणि हस्तनिर्मित शेणा-मातीचे सारवलेले अंगण साकारले असून त्यावर तांदळाच्या पिठाची पारंपरिक रांगोळी काढली आहे.',
    materialsUsed: '१००% कागदी लगदा मूर्ती, सुपारीच्या झावळ्या, नारळाच्या करवंट्या, सुका भाताचा पेंढा, तांदळाच्या पिठाची रांगोळी, शेण-मातीचे सारवण.',
    photoUrls: [],
    entryFee: 99,
    paymentStatus: 'COMPLETED',
    status: 'APPROVED',
    finalScore: 8.5,
    finalRank: 8,
    evaluationsCount: 2,
    createdAt: '2026-09-06T14:30:00Z',
  },
  {
    id: 'entry-109',
    ticketId: 'LOK-2026-157887',
    fullName: 'Nilesh Baburao Gaikwad',
    phone: '9822667788',
    email: 'nilesh.gaikwad@example.com',
    district: 'Solapur',
    city: 'Jule Solapur, Solapur',
    address: 'Near Siddheshwar Temple, Solapur 413004',
    category: 'SARVAJANIK_MANDAL',
    idolType: 'SHADU_MATI_CLAY',
    themeTitle: 'सोलापूर हातमाग चादर व विणकर संस्कृती सन्मान देखावा (Solapur Handloom Weavers & Sustainable Khadi Legacy)',
    themeDescription: 'महाराष्ट्राच्या जागतिक कीर्तीच्या सोलापुरी चादर आणि हातमाग विणकर परंपरेला समर्पित कलात्मक देखावा. १००% शुद्ध सुती धागे, अस्सल लाकडी माग (Shuttle Handloom) आणि नैसर्गिक वनस्पतींपासून काढलेल्या (घायपात, हळद, डाळिंब साल) रंगीत धाग्यांच्या ताण्या-बाण्यातून गणरायाची भव्य महिरप व मंडप गुंफण्यात आला आहे.',
    materialsUsed: '१००% शाडू माती मूर्ती, शुद्ध खादी व हातमाग सुती कापड, लाकडी विणकाम साचा, नैसर्गिक भाजलेली मातीची भांडी, सौरऊर्जा दिवे.',
    photoUrls: [],
    entryFee: 99,
    paymentStatus: 'COMPLETED',
    status: 'APPROVED',
    finalScore: 8.4,
    finalRank: 9,
    evaluationsCount: 2,
    createdAt: '2026-09-07T11:20:00Z',
  },
  {
    id: 'entry-110',
    ticketId: 'LOK-2026-240821',
    fullName: 'Digambar Madhav Sahasrabuddhe',
    phone: '9890778899',
    email: 'digambar.sahasrabuddhe@example.com',
    district: 'Amravati',
    city: 'Rajarampeth, Amravati',
    address: 'Camp Area, Amravati 444602',
    category: 'HOUSEHOLD',
    idolType: 'SHADU_MATI_CLAY',
    themeTitle: 'मेळघाट व्याघ्र संवर्धन, कोरकू आदिवासी कला व बांबू हस्तकला (Melghat Wilderness & Korku Tribal Bamboo Artistry)',
    themeDescription: 'सातपुड्याच्या पर्वतरांगेतील मेळघाटचे घनदाट जंगल आणि स्थानिक कोरकू आदिवासी बांधवांच्या पारंपरिक हस्तकलेला मानाचा मुजरा. स्थानिक जंगलातील बांबूच्या बारीक विणकामाच्या टोपल्या, गवताचे पडदे, जंगलातील सागाच्या पानांचे तोरण आणि आदिवासी वारली-कोरकू भित्तीचित्रांच्या माध्यमातून वन्यजीव रक्षण व वनवासी संस्कृतीचा हृदयस्पर्शी संदेश दिला आहे.',
    materialsUsed: '१००% शाडू माती मूर्ती, स्थानिक सातपुडा बांबू, नैसर्गिक ताग, कोरकू सेंद्रिय भित्तीचित्र रंग, वाळलेल्या औषधी बिया, मातीचे कंदील.',
    photoUrls: [],
    entryFee: 99,
    paymentStatus: 'COMPLETED',
    status: 'APPROVED',
    finalScore: 8.3,
    finalRank: 10,
    evaluationsCount: 2,
    createdAt: '2026-09-07T16:45:00Z',
  },
];
