import { ParticipantEntry, SponsorItem, PrizeItem, Criterion } from './types';

export const OFFICIAL_PRIZES: PrizeItem[] = [
  {
    rank: 1,
    title: 'Maharashtra Rajya Mahavijeta (1st Place)',
    titleMr: 'महाराष्ट्र राज्य महाविजेता (प्रथम क्रमांक)',
    cashAmount: 51000,
    cashText: '₹51,000 Cash',
    cashTextMr: '₹51,000 रोख पारितोषिक',
    perks: ['Grand Gold Plated Trophy', 'Title Sponsor Gift Hamper worth ₹15,000', 'State-wide Media Coverage', 'Certificate of Honor'],
    perksMr: ['मानाची सुवर्णजडित ट्रॉफी', 'मुख्य प्रायोजकांकडून ₹15,000 चा विशेष हॅम्पर', 'राज्यस्तरीय वृत्तपत्र व माध्यम प्रसिद्धी', 'अधिकृत सन्मानपत्र'],
    badgeColor: 'bg-amber-600 text-white',
  },
  {
    rank: 2,
    title: '2nd Place (Dvitiya Puraskar)',
    titleMr: 'द्वितीय क्रमांक',
    cashAmount: 31000,
    cashText: '₹31,000 Cash',
    cashTextMr: '₹31,000 रोख पारितोषिक',
    perks: ['Silver Plated Trophy', 'Sponsor Hamper worth ₹10,000', 'Certificate of Honor'],
    perksMr: ['मानाची रजत ट्रॉफी', 'प्रायोजकांकडून ₹10,000 चा हॅम्पर', 'अधिकृत सन्मानपत्र'],
    badgeColor: 'bg-slate-500 text-white',
  },
  {
    rank: 3,
    title: '3rd Place (Tritiya Puraskar)',
    titleMr: 'तृतीय क्रमांक',
    cashAmount: 21000,
    cashText: '₹21,000 Cash',
    cashTextMr: '₹21,000 रोख पारितोषिक',
    perks: ['Bronze Plated Trophy', 'Sponsor Hamper worth ₹7,500', 'Certificate of Honor'],
    perksMr: ['कांस्य ट्रॉफी', 'प्रायोजकांकडून ₹7,500 चा हॅम्पर', 'अधिकृत सन्मानपत्र'],
    badgeColor: 'bg-amber-800 text-white',
  },
  {
    rank: 4,
    title: '4th to 10th Place (State Consolation Awards)',
    titleMr: '4था ते 10वा क्रमांक (राज्यस्तरीय गुणवत्ता पुरस्कार)',
    cashAmount: 5000,
    cashText: '₹5,000 Cash Each (7 Winners)',
    cashTextMr: 'प्रत्येकी ₹5,000 रोख (7 विजेते)',
    perks: ['Maha Lokutsav Memento', 'Sponsor Gift Box', 'Certificate of Merit'],
    perksMr: ['महा लोकोत्सव सन्मानचिन्ह', 'प्रायोजक गिफ्ट बॉक्स', 'गुणवत्ता प्रमाणपत्र'],
    badgeColor: 'bg-stone-700 text-white',
  },
];

export const JUDGING_CRITERIA_LIST: Criterion[] = [
  {
    id: 'crit-1',
    name: 'Concept & Creativity',
    nameMr: 'संकल्पना व कल्पकता',
    description: 'Originality of story, theme, cultural resonance, and depth of imagination.',
    descriptionMr: 'सजावटीमागील मूळ विचार, संदेश, सामाजिक किंवा पौराणिक संकल्पनेची मांडणी.',
    maxScore: 10,
    weight: 0.25,
    iconName: 'Sparkles',
  },
  {
    id: 'crit-2',
    name: 'Craftsmanship & Detailing',
    nameMr: 'हस्तकला व फिनिशिंग',
    description: 'Structural precision, finishing, artistry, handmade elements, and aesthetic balance.',
    descriptionMr: 'तयार केलेल्या देखाव्याची कारागिरी, अचूकता, सुबकता आणि सुसंवाद.',
    maxScore: 10,
    weight: 0.25,
    iconName: 'Palette',
  },
  {
    id: 'crit-3',
    name: 'Eco-Friendliness & Materials',
    nameMr: 'पर्यावरणपूरकता व साहित्य',
    description: 'Clay (Shadu) idol, cloth, bamboo, paper pulp, seed paper; zero thermocol or plastic.',
    descriptionMr: 'शाडू माती मूर्ती, कागदी लगदा, फुले, कापड यांसारख्या निसर्गस्नेही घटकांचा वापर.',
    maxScore: 10,
    weight: 0.20,
    iconName: 'Leaf',
  },
  {
    id: 'crit-4',
    name: 'Lighting & Presentation',
    nameMr: 'प्रकाशयोजना व सादरीकरण',
    description: 'Lighting design, color coherence, neatness, framing, and visual ambience.',
    descriptionMr: 'रंगसंगती, प्रकाशयोजना (Lighting), मांडणीचे सौंदर्य आणि संपूर्ण दृश्य प्रभाव.',
    maxScore: 10,
    weight: 0.15,
    iconName: 'Sun',
  },
  {
    id: 'crit-5',
    name: 'Uniqueness & Wow Factor',
    nameMr: 'नाविन्यता व वेगळेपण',
    description: 'Novel approach, emotional impact, and unforgettable artistic impression.',
    descriptionMr: 'नेहमीपेक्षा वेगळा विचार आणि प्रेक्षकांना मंत्रमुग्ध करणारी नाविन्यपूर्ण कल्पना.',
    maxScore: 10,
    weight: 0.15,
    iconName: 'Award',
  },
];

export const SPONSORS_LIST: SponsorItem[] = [
  {
    id: 'sp-1',
    name: 'Chitale Bandhu Mithaiwale',
    tier: 'TITLE',
    logoUrl: '/sponsors/chitale.png',
    websiteUrl: 'https://chitalebandhu.in',
    sponsoredCategory: 'Title Partner & Grand 1st Prize',
    sponsoredCategoryMr: 'मुख्य प्रायोजक व महाविजेता पारितोषिक',
    description: 'Maharashtra’s iconic heritage sweetmaker celebrating sweet traditions for over 8 decades.',
    descriptionMr: 'महाराष्ट्राचे लाडके मिष्ठान्न ब्रँड, 8 दशकांपासून परंपरेची गोडी जपणारे चितळे बंधू.',
  },
  {
    id: 'sp-2',
    name: 'PNG Jewellers',
    tier: 'POWERED_BY',
    logoUrl: '/sponsors/png.png',
    websiteUrl: 'https://pngjewellers.com',
    sponsoredCategory: 'Official Trophy & Gold Partner',
    sponsoredCategoryMr: 'अधिकृत सुवर्ण ट्रॉफी व सह-प्रायोजक',
    description: 'Purity, Trust and 190+ years of Royal Maharashtrian Jewellery legacy.',
    descriptionMr: 'शुद्धता, विश्वास आणि 190+ वर्षांचा सुवर्ण वारसा जपणारे पी एन जी ज्वेलर्स.',
  },
  {
    id: 'sp-3',
    name: 'Suhana Spices',
    tier: 'GOLD',
    logoUrl: '/sponsors/suhana.png',
    websiteUrl: 'https://suhana.co.in',
    sponsoredCategory: 'Best Eco-Friendly Decoration Award',
    sponsoredCategoryMr: 'सर्वोत्कृष्ट पर्यावरणपूरक सजावट पुरस्कार',
    description: 'Delivering authentic flavors and fragrant Maharashtrian masalas worldwide.',
    descriptionMr: 'घरचा अस्सल स्वाद आणि रुचकर खाद्यपरंपरेचा सुगंध देणारे सुहाना मसाले.',
  },
  {
    id: 'sp-4',
    name: 'Saraswat Bank',
    tier: 'ASSOCIATE',
    logoUrl: '/sponsors/saraswat.png',
    websiteUrl: 'https://saraswatbank.com',
    sponsoredCategory: 'Digital Banking & Verification Partner',
    sponsoredCategoryMr: 'डिजिटल बँकिंग व पडताळणी सहयोगी',
    description: 'India’s largest urban co-operative bank supporting Marathi culture and enterprise.',
    descriptionMr: 'महाराष्ट्राच्या प्रगतीचा विश्वासू भागीदार, सर्वात मोठी अग्रगण्य सहकारी बँक.',
  },
];

export const INITIAL_ENTRIES: ParticipantEntry[] = [
  {
    id: 'entry-101',
    ticketId: 'LOK-2026-7812',
    fullName: 'Shrikant Ramchandra Joshi',
    phone: '9822019941',
    email: 'shrikant.joshi@example.com',
    district: 'Pune',
    city: 'Sadashiv Peth, Pune',
    address: 'Flat 4, Shreeram Niwas, Perugate, Pune 411030',
    category: 'HOUSEHOLD',
    idolType: 'SHADU_MATI_CLAY',
    themeTitle: 'Historic Raigad Darbar with Eco-friendly Handwoven Jute & Terracotta',
    themeDescription: 'We recreated Chhatrapati Shivaji Maharaj’s iconic Meghadambari and throne using only discarded cardboard, jute rope, coconut shells, and clay pots. Lord Ganesha sits in the royal court radiating grace.',
    materialsUsed: 'Shadu mati idol, bamboo sticks, jute rope, dried marigold powder for organic colors, terracotta diyas.',
    photoUrls: [
      'https://images.unsplash.com/photo-1567591370504-20a2e7c54ef5?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1599827552599-eafeedb4231f?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1600093463592-8e36ae95ef56?auto=format&fit=crop&w=1200&q=80',
    ],
    videoUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    entryFee: 199,
    paymentStatus: 'COMPLETED',
    razorpayOrderId: 'order_Pune_9012',
    razorpayPaymentId: 'pay_Pune_8911',
    status: 'APPROVED',
    finalScore: 9.6,
    finalRank: 1,
    evaluationsCount: 4,
    createdAt: '2026-09-02T10:30:00Z',
  },
  {
    id: 'entry-102',
    ticketId: 'LOK-2026-6543',
    fullName: 'Vaishali Anand Salunkhe',
    phone: '9765412390',
    email: 'vaishali.salunkhe@example.com',
    district: 'Kolhapur',
    city: 'Rajarampuri, Kolhapur',
    address: 'Plot 12, Tarabai Park, Kolhapur 416003',
    category: 'HOUSEHOLD',
    idolType: 'SHADU_MATI_CLAY',
    themeTitle: 'Ambabai Mahalakshmi Deepstambh & Brass Temple Architecture',
    themeDescription: 'A miniature stone replica of the historic Kolhapur Mahalakshmi temple facade illuminated with 108 oil brass lamps and brass bells made from sustainable wood and brass polish.',
    materialsUsed: 'Handmade clay tiles, recycled wood, organic turmeric and kumkum paints, brass lamps.',
    photoUrls: [
      'https://images.unsplash.com/photo-1606293926075-69a00dbfde81?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1567591370504-20a2e7c54ef5?auto=format&fit=crop&w=1200&q=80',
    ],
    videoUrl: 'https://www.youtube.com/watch?v=sample2',
    entryFee: 199,
    paymentStatus: 'COMPLETED',
    razorpayOrderId: 'order_Kolhapur_3211',
    razorpayPaymentId: 'pay_Kolhapur_4432',
    status: 'APPROVED',
    finalScore: 9.4,
    finalRank: 2,
    evaluationsCount: 3,
    createdAt: '2026-09-03T14:15:00Z',
  },
  {
    id: 'entry-103',
    ticketId: 'LOK-2026-8921',
    fullName: 'Mangesh Devidas Parab',
    phone: '9820156789',
    email: 'mangesh.parab@example.com',
    district: 'Mumbai Suburban',
    city: 'Vile Parle East, Mumbai',
    address: 'B-14, Shree Ganesh Krupa, Hanuman Road, Mumbai 400057',
    category: 'HOUSEHOLD',
    idolType: 'ECO_FRIENDLY_PAPER_PULP',
    themeTitle: 'Warkari Sant Samagam - Alandi to Pandharpur Pilgrimage Diorama',
    themeDescription: 'Featuring 40 miniature paper-pulp Warkari figures carrying the Palkhi, playing taal and veena with moving LED ambient dawn light mimicking the Indrayani riverbank.',
    materialsUsed: 'Old newspapers, wheat flour paste (layi), wooden sticks, cotton robes for figurines.',
    photoUrls: [
      'https://images.unsplash.com/photo-1599827552599-eafeedb4231f?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1600093463592-8e36ae95ef56?auto=format&fit=crop&w=1200&q=80',
    ],
    videoUrl: 'https://www.youtube.com/watch?v=sample3',
    entryFee: 199,
    paymentStatus: 'COMPLETED',
    razorpayOrderId: 'order_Mumbai_1190',
    razorpayPaymentId: 'pay_Mumbai_7721',
    status: 'APPROVED',
    finalScore: 9.2,
    finalRank: 3,
    evaluationsCount: 3,
    createdAt: '2026-09-04T09:00:00Z',
  },
  {
    id: 'entry-104',
    ticketId: 'LOK-2026-4411',
    fullName: 'Aniket Surendra Deshmukh',
    phone: '9422334455',
    email: 'aniket.d@example.com',
    district: 'Nagpur',
    city: 'Dharampeth, Nagpur',
    address: '22, Orange City Enclave, Nagpur 440010',
    category: 'HOUSEHOLD',
    idolType: 'SHADU_MATI_CLAY',
    themeTitle: 'Tadoba Forest Sanctuary & Environmental Conservation Theme',
    themeDescription: 'Highlighting nature conservation with natural leaves, real potted plants, and wooden tree bark structures around Bappa to spread the message of preserving Vidarbha forest corridors.',
    materialsUsed: 'Live medicinal plants (Tulsi, Durva, Bel), coconut coir, tree bark, fallen dry leaves.',
    photoUrls: [
      'https://images.unsplash.com/photo-1606293926075-69a00dbfde81?auto=format&fit=crop&w=1200&q=80',
    ],
    entryFee: 199,
    paymentStatus: 'COMPLETED',
    razorpayOrderId: 'order_Nagpur_7712',
    razorpayPaymentId: 'pay_Nagpur_9921',
    status: 'APPROVED',
    finalScore: 8.9,
    finalRank: 4,
    evaluationsCount: 2,
    createdAt: '2026-09-04T16:20:00Z',
  },
  {
    id: 'entry-105',
    ticketId: 'LOK-2026-3392',
    fullName: 'Suhas Eknath Kadam',
    phone: '9921345566',
    email: 'suhas.kadam@example.com',
    district: 'Satara',
    city: 'Wai, Satara',
    address: 'Ghat Road, Wai, Satara 412803',
    category: 'HOUSEHOLD',
    idolType: 'SHADU_MATI_CLAY',
    themeTitle: 'Krishna River Ghat & Dhol-Tasha Heritage Presentation',
    themeDescription: 'Crafted stone steps representing Wai Ghat on the Krishna river, miniature hand-carved Dhol and Tasha instruments made by local artisans.',
    materialsUsed: 'Clay stones, miniature wood instruments, brass bells, natural river sand.',
    photoUrls: [
      'https://images.unsplash.com/photo-1567591370504-20a2e7c54ef5?auto=format&fit=crop&w=1200&q=80',
    ],
    entryFee: 199,
    paymentStatus: 'COMPLETED',
    razorpayOrderId: 'order_Satara_3411',
    razorpayPaymentId: 'pay_Satara_8871',
    status: 'APPROVED',
    finalScore: 8.8,
    finalRank: 5,
    evaluationsCount: 2,
    createdAt: '2026-09-05T11:45:00Z',
  },
  {
    id: 'entry-106',
    ticketId: 'LOK-2026-5590',
    fullName: 'Balasaheb Tukaram More',
    phone: '9890123456',
    email: 'balasaheb.more@example.com',
    district: 'Nashik',
    city: 'Panchavati, Nashik',
    address: 'Ramkund Parisar, Panchavati, Nashik 422003',
    category: 'SARVAJANIK_MANDAL',
    idolType: 'SHADU_MATI_CLAY',
    themeTitle: 'Godavari Jal Sanrakshan (Water Conservation Mission)',
    themeDescription: 'Sarvajanik mandal decoration depicting river restoration, rainwater harvesting techniques, and clean Godavari campaign.',
    materialsUsed: 'Khadi cloth backdrop, water fountain using recirculated water, handmade paper boards.',
    photoUrls: [
      'https://images.unsplash.com/photo-1599827552599-eafeedb4231f?auto=format&fit=crop&w=1200&q=80',
    ],
    entryFee: 199,
    paymentStatus: 'COMPLETED',
    razorpayOrderId: 'order_Nashik_9011',
    razorpayPaymentId: 'pay_Nashik_3311',
    status: 'APPROVED',
    finalScore: 8.7,
    finalRank: 6,
    evaluationsCount: 2,
    createdAt: '2026-09-05T15:10:00Z',
  },
];
